--------------------------------------------------------
--  파일이 생성됨 - 일요일-7월-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN_INFO
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."ADMIN_INFO" 
   (	"ADMIN_NO" NUMBER, 
	"ADMIN_EMAIL" VARCHAR2(50 BYTE), 
	"ADMIN_PW" VARCHAR2(50 BYTE), 
	"ADMIN_NICK" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "GREEN_ADMIN"."ADMIN_INFO"."ADMIN_NO" IS '관리자번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."ADMIN_INFO"."ADMIN_EMAIL" IS '관리자메일아이디';
   COMMENT ON COLUMN "GREEN_ADMIN"."ADMIN_INFO"."ADMIN_PW" IS '관리자비밀번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."ADMIN_INFO"."ADMIN_NICK" IS '관리자별명
';
REM INSERTING into GREEN_ADMIN.ADMIN_INFO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADMIN_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."ADMIN_INFO_PK" ON "GREEN_ADMIN"."ADMIN_INFO" ("ADMIN_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007282
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."SYS_C007282" ON "GREEN_ADMIN"."ADMIN_INFO" ("ADMIN_NO", "ADMIN_EMAIL", "ADMIN_PW", "ADMIN_NICK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMIN_INFO
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."ADMIN_INFO" ADD UNIQUE ("ADMIN_NO", "ADMIN_EMAIL", "ADMIN_PW", "ADMIN_NICK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."ADMIN_INFO" ADD CONSTRAINT "ADMIN_INFO_PK" PRIMARY KEY ("ADMIN_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."ADMIN_INFO" MODIFY ("ADMIN_NICK" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."ADMIN_INFO" MODIFY ("ADMIN_PW" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."ADMIN_INFO" MODIFY ("ADMIN_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."ADMIN_INFO" MODIFY ("ADMIN_NO" NOT NULL ENABLE);
