--------------------------------------------------------
--  파일이 생성됨 - 일요일-7월-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMMUNITY_COMMENT
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."COMMUNITY_COMMENT" 
   (	"COMM_NO" NUMBER, 
	"COMM_WRITER" VARCHAR2(20 BYTE), 
	"COMM_TEXT" CLOB, 
	"COMM_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("COMM_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY_COMMENT"."COMM_NO" IS '커뮤댓글번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY_COMMENT"."COMM_WRITER" IS '커뮤댓글작성자';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY_COMMENT"."COMM_TEXT" IS '커뮤댓글본문';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY_COMMENT"."COMM_DATE" IS '커뮤댓글작성일';
REM INSERTING into GREEN_ADMIN.COMMUNITY_COMMENT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index COMMUNITY_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."COMMUNITY_COMMENT_PK" ON "GREEN_ADMIN"."COMMUNITY_COMMENT" ("COMM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMMUNITY_COMMENT
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."COMMUNITY_COMMENT" ADD CONSTRAINT "COMMUNITY_COMMENT_PK" PRIMARY KEY ("COMM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY_COMMENT" MODIFY ("COMM_DATE" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY_COMMENT" MODIFY ("COMM_TEXT" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY_COMMENT" MODIFY ("COMM_WRITER" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY_COMMENT" MODIFY ("COMM_NO" NOT NULL ENABLE);
