--------------------------------------------------------
--  파일이 생성됨 - 일요일-7월-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMMUNITY
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."COMMUNITY" 
   (	"COMMU_NO" NUMBER, 
	"COMMU_TAG" VARCHAR2(20 BYTE), 
	"COMMU_TITLE" VARCHAR2(100 BYTE), 
	"COMMU_WRITER" VARCHAR2(20 BYTE), 
	"COMMU_TEXT" CLOB, 
	"COMMU_DATE" DATE, 
	"COMMU_VIEW" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("COMMU_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_NO" IS '커뮤글번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_TAG" IS '커뮤글말머리';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_TITLE" IS '커뮤글제목';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_WRITER" IS '커뮤글작성자';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_TEXT" IS '커뮤글본문';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_DATE" IS '커뮤글작성일';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_VIEW" IS '커뮤글조회수';
REM INSERTING into GREEN_ADMIN.COMMUNITY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index NEWS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."NEWS_PK" ON "GREEN_ADMIN"."COMMUNITY" ("COMMU_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMMUNITY
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."COMMUNITY" ADD CONSTRAINT "NEWS_PK" PRIMARY KEY ("COMMU_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY" MODIFY ("COMMU_DATE" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY" MODIFY ("COMMU_WRITER" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY" MODIFY ("COMMU_TITLE" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY" MODIFY ("COMMU_TAG" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY" MODIFY ("COMMU_NO" NOT NULL ENABLE);
