--------------------------------------------------------
--  파일이 생성됨 - 일요일-7월-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GOODS
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."GOODS" 
   (	"GOODS_NO" NUMBER, 
	"GOODS_NAME" VARCHAR2(50 BYTE), 
	"GOODS_SIZE" VARCHAR2(20 BYTE), 
	"GOODS_TYPE" VARCHAR2(20 BYTE), 
	"GOODS_PRICE" NUMBER, 
	"GOODS_EFFICIENT" NUMBER, 
	"GOODS_FUEL" VARCHAR2(20 BYTE), 
	"BRAND_CODE" NUMBER, 
	"GOODS_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_NO" IS '상품번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_NAME" IS '상품차량명';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_SIZE" IS '상품차량차종';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_TYPE" IS '상품차량타입';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_PRICE" IS '상품가격';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_EFFICIENT" IS '상품차량연비';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_FUEL" IS '상품차량연료

';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."BRAND_CODE" IS '상품차량브랜드코드';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_CODE" IS '상품코드
';
REM INSERTING into GREEN_ADMIN.GOODS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index GOODS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."GOODS_PK" ON "GREEN_ADMIN"."GOODS" ("GOODS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007293
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."SYS_C007293" ON "GREEN_ADMIN"."GOODS" ("GOODS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GOODS
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."GOODS" ADD UNIQUE ("GOODS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."GOODS" ADD CONSTRAINT "GOODS_PK" PRIMARY KEY ("GOODS_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."GOODS" MODIFY ("GOODS_NO" NOT NULL ENABLE);
