--------------------------------------------------------
--  파일이 생성됨 - 일요일-7월-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GOODS_OPTION
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."GOODS_OPTION" 
   (	"OPTION_NO" NUMBER, 
	"OPTION_NAME" VARCHAR2(50 BYTE), 
	"OPTION_COLOR" VARCHAR2(50 BYTE), 
	"OPTION_TIRE" VARCHAR2(50 BYTE), 
	"OPTION_WHEEL" VARCHAR2(50 BYTE), 
	"OPTION_NAVI" CHAR(1 BYTE), 
	"OPTION_SEAT" VARCHAR2(50 BYTE), 
	"OPTION_FRAME" VARCHAR2(50 BYTE), 
	"OPTION_WINDOW" VARCHAR2(50 BYTE), 
	"OPTION_COST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_NO" IS '옵션번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_NAME" IS '옵션명';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_COLOR" IS '색상옵션';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_TIRE" IS '타이어옵션';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_WHEEL" IS '휠옵션';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_NAVI" IS '네비유무';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_SEAT" IS '시트옵션';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_FRAME" IS '프레입옵션';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_WINDOW" IS '창문옵션';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_COST" IS '옵션가격';
REM INSERTING into GREEN_ADMIN.GOODS_OPTION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index GOODS_OPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."GOODS_OPTION_PK" ON "GREEN_ADMIN"."GOODS_OPTION" ("OPTION_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007305
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."SYS_C007305" ON "GREEN_ADMIN"."GOODS_OPTION" ("OPTION_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GOODS_OPTION
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" ADD UNIQUE ("OPTION_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" ADD CONSTRAINT "GOODS_OPTION_PK" PRIMARY KEY ("OPTION_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_COST" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_WINDOW" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_FRAME" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_SEAT" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_NAVI" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_WHEEL" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_TIRE" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_COLOR" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_NAME" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_NO" NOT NULL ENABLE);
