--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-14-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN_INFO
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."ADMIN_INFO" 
   (	"ADMIN_NO" NUMBER, 
	"ADMIN_EMAIL" VARCHAR2(50 BYTE), 
	"ADMIN_PW" VARCHAR2(50 BYTE), 
	"ADMIN_NICK" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "GREEN_ADMIN"."ADMIN_INFO"."ADMIN_NO" IS '관리자번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."ADMIN_INFO"."ADMIN_EMAIL" IS '관리자메일아이디';
   COMMENT ON COLUMN "GREEN_ADMIN"."ADMIN_INFO"."ADMIN_PW" IS '관리자비밀번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."ADMIN_INFO"."ADMIN_NICK" IS '관리자별명
';
--------------------------------------------------------
--  DDL for Table BRAND
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."BRAND" 
   (	"BRAND_NO" NUMBER, 
	"BRAND_NAME" VARCHAR2(30 BYTE), 
	"BRAND_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMUNITY
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."COMMUNITY" 
   (	"COMMU_NO" NUMBER, 
	"COMMU_TAG" VARCHAR2(20 BYTE), 
	"COMMU_TITLE" VARCHAR2(100 BYTE), 
	"COMMU_WRITER" VARCHAR2(50 BYTE), 
	"COMMU_TEXT" CLOB, 
	"COMMU_DATE" DATE, 
	"COMMU_VIEW" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("COMMU_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_NO" IS '커뮤글번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_TAG" IS '커뮤글말머리';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_TITLE" IS '커뮤글제목';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_WRITER" IS '커뮤글작성자';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_TEXT" IS '커뮤글본문';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_DATE" IS '커뮤글작성일';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY"."COMMU_VIEW" IS '커뮤글조회수';
--------------------------------------------------------
--  DDL for Table COMMUNITY_COMMENT
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."COMMUNITY_COMMENT" 
   (	"COMM_NO" NUMBER, 
	"COMM_WRITER" VARCHAR2(20 BYTE), 
	"COMM_TEXT" CLOB, 
	"COMM_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("COMM_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY_COMMENT"."COMM_NO" IS '커뮤댓글번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY_COMMENT"."COMM_WRITER" IS '커뮤댓글작성자';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY_COMMENT"."COMM_TEXT" IS '커뮤댓글본문';
   COMMENT ON COLUMN "GREEN_ADMIN"."COMMUNITY_COMMENT"."COMM_DATE" IS '커뮤댓글작성일';
--------------------------------------------------------
--  DDL for Table GOODS
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."GOODS" 
   (	"GOODS_NO" NUMBER, 
	"GOODS_NAME" VARCHAR2(50 BYTE), 
	"GOODS_SIZE" VARCHAR2(20 BYTE), 
	"GOODS_TYPE" VARCHAR2(20 BYTE), 
	"GOODS_PRICE" NUMBER, 
	"GOODS_EFFICIENT" NUMBER, 
	"GOODS_FUEL" VARCHAR2(20 BYTE), 
	"BRAND_CODE" NUMBER, 
	"GOODS_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_NO" IS '상품번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_NAME" IS '상품차량명';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_SIZE" IS '상품차량차종';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_TYPE" IS '상품차량타입';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_PRICE" IS '상품가격';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_EFFICIENT" IS '상품차량연비';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_FUEL" IS '상품차량연료

';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."BRAND_CODE" IS '상품차량브랜드코드';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS"."GOODS_CODE" IS '상품코드
';
--------------------------------------------------------
--  DDL for Table GOODS_OPTION
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."GOODS_OPTION" 
   (	"OPTION_NO" NUMBER, 
	"OPTION_NAME" VARCHAR2(50 BYTE), 
	"OPTION_TIRE" VARCHAR2(50 BYTE), 
	"OPTION_WHEEL" VARCHAR2(50 BYTE), 
	"OPTION_NAVI" CHAR(1 BYTE), 
	"OPTION_SEAT" VARCHAR2(50 BYTE), 
	"OPTION_FRAME" VARCHAR2(50 BYTE), 
	"OPTION_WINDOW" VARCHAR2(50 BYTE), 
	"OPTION_COST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_NO" IS '옵션번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_NAME" IS '옵션명';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_TIRE" IS '타이어옵션';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_WHEEL" IS '휠옵션';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_NAVI" IS '네비유무';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_SEAT" IS '시트옵션';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_FRAME" IS '프레입옵션';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_WINDOW" IS '창문옵션';
   COMMENT ON COLUMN "GREEN_ADMIN"."GOODS_OPTION"."OPTION_COST" IS '옵션가격';
--------------------------------------------------------
--  DDL for Table NEWS
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."NEWS" 
   (	"NEWS_NO" NUMBER, 
	"NEWS_TITLE" VARCHAR2(500 BYTE), 
	"NEWS_TEXT" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("NEWS_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."NOTICE" 
   (	"NOTICE_NO" NUMBER, 
	"NOTICE_TITLE" VARCHAR2(200 BYTE), 
	"NOTICE_TEXT" CLOB, 
	"NOTICE_WRITER" VARCHAR2(20 BYTE), 
	"UPLOAD_DATE" DATE DEFAULT sysdate, 
	"NOTICE_VIEW" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("NOTICE_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "GREEN_ADMIN"."NOTICE"."NOTICE_NO" IS '공지글번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."NOTICE"."NOTICE_TITLE" IS '공지글제목';
   COMMENT ON COLUMN "GREEN_ADMIN"."NOTICE"."NOTICE_TEXT" IS '공지글본문
';
   COMMENT ON COLUMN "GREEN_ADMIN"."NOTICE"."NOTICE_WRITER" IS '공지글작성자';
   COMMENT ON COLUMN "GREEN_ADMIN"."NOTICE"."UPLOAD_DATE" IS '공지글게시일';
   COMMENT ON COLUMN "GREEN_ADMIN"."NOTICE"."NOTICE_VIEW" IS '공지글조회수';
--------------------------------------------------------
--  DDL for Table SALES_DATA
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."SALES_DATA" 
   (	"COLUMN1" DATE, 
	"SALES_COST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "GREEN_ADMIN"."SALES_DATA"."COLUMN1" IS '판매월';
   COMMENT ON COLUMN "GREEN_ADMIN"."SALES_DATA"."SALES_COST" IS '매출액';
--------------------------------------------------------
--  DDL for Table USER_INFO
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."USER_INFO" 
   (	"USER_NO" NUMBER, 
	"USER_EMAIL" VARCHAR2(50 BYTE), 
	"USER_PW" VARCHAR2(50 BYTE), 
	"USER_NICK" VARCHAR2(50 BYTE), 
	"USER_BIRTH" NUMBER(8,0), 
	"USER_PH" NUMBER(11,0), 
	"USER_ADDRESS" VARCHAR2(50 BYTE), 
	"USER_ADDRESS_DETAIL" VARCHAR2(50 BYTE), 
	"USER_JOIN_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_NO" IS '고객번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_EMAIL" IS '고객메일아이디';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_PW" IS '고객비밇번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_NICK" IS '고객닉네임';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_BIRTH" IS '고객생년월일';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_PH" IS '고객핸드폰번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_ADDRESS" IS '고객 기본주소';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_ADDRESS_DETAIL" IS '고객 상세주소
';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_JOIN_DATE" IS '고객가입일자';
--------------------------------------------------------
--  DDL for Table USER_INQUIRY
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."USER_INQUIRY" 
   (	"INQUIRY_NO" NUMBER, 
	"INQUIRY_TAG" VARCHAR2(20 BYTE), 
	"INQUIRY_TITLE" VARCHAR2(100 BYTE), 
	"INQUIRY_TEXT" CLOB, 
	"INQUIRY_DATE" DATE DEFAULT sysdate, 
	"INQUIRY_WRITER" VARCHAR2(50 BYTE), 
	"INQUIRY_ANSWER" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("INQUIRY_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("INQUIRY_ANSWER") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_NO" IS '고객문의번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_TAG" IS '문의유형';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_TITLE" IS '문의제목';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_TEXT" IS '문의본문';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_DATE" IS '문의일';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_WRITER" IS '문의고객명';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_ANSWER" IS '문의답변';
REM INSERTING into GREEN_ADMIN.ADMIN_INFO
SET DEFINE OFF;
Insert into GREEN_ADMIN.ADMIN_INFO (ADMIN_NO,ADMIN_EMAIL,ADMIN_PW,ADMIN_NICK) values (1,'admin@greencar.com','admin','관리자');
REM INSERTING into GREEN_ADMIN.BRAND
SET DEFINE OFF;
REM INSERTING into GREEN_ADMIN.COMMUNITY
SET DEFINE OFF;
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (1,'시승기','만삭임산부 폭행','행복사랑',to_date('2020-07-01','YYYY-MM-DD'),37);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (2,'시승기','일본 수해 피해 도와줘라','순정마초',to_date('2020-07-02','YYYY-MM-DD'),23);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (3,'시승기','YTN인 이유','유재석',to_date('2020-07-03','YYYY-MM-DD'),583);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (4,'유머','일본 물난리에 냉소적인 이유','강호호호호동',to_date('2020-07-04','YYYY-MM-DD'),247);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (5,'유머','공영주차장 불법 점거..','만두먹방',to_date('2020-07-05','YYYY-MM-DD'),93);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (6,'유머','(고)최숙현을 절망시킨 경주경찰의 말','그린컴컴',to_date('2020-07-06','YYYY-MM-DD'),3);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (7,'유머','팀닥터 진짜 정체','페라리오너',to_date('2020-07-07','YYYY-MM-DD'),277);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (8,'구매후기','21살의 꽃다운 나이에 억울하게 죽어간 고 이형준하사를 도와주세요!','카푸어',to_date('2020-07-08','YYYY-MM-DD'),1438);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (9,'구매후기','피아노 없이 피아노를 배운 한 소녀의 이야기','동네바보',to_date('2020-07-09','YYYY-MM-DD'),873);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (10,'구매후기','장애인 주차구역을 막지 맙시다. 상식은 지키는 사람이길','사랑꾼',to_date('2020-07-10','YYYY-MM-DD'),999);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (11,'유머','에어팟 애플스토어에서 샀어도 정품등록 해야해?','숨마쿰라우데',to_date('2020-07-11','YYYY-MM-DD'),44);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (13,'유머','이별했는데 울면 근손실오냐','강규림',to_date('2020-07-13','YYYY-MM-DD'),22);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (17,'유머','얼어 죽어도 아이스 아메리카노','내꿈은건물주',to_date('2020-06-01','YYYY-MM-DD'),22);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (18,'유머','나 카페 알바하는데 이날씨에 뜨거운 아메리 먹는 사람 있음','야채곱창',to_date('2020-06-02','YYYY-MM-DD'),111);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (19,'유머','주식 어떻게 시작해?','신림사는규림',to_date('2020-06-03','YYYY-MM-DD'),54);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (20,'유머','북한산 갈건데 맛집추천좀','사근진해변',to_date('2020-06-04','YYYY-MM-DD'),21);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (21,'유머','담배좀끊어라','메머드',to_date('2020-06-05','YYYY-MM-DD'),1);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (22,'유머','올여름 수영장 못가겠지?','나는공주',to_date('2020-06-06','YYYY-MM-DD'),22);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (23,'유머','콘솔게임 추천좀','불타는독수리',to_date('2020-06-07','YYYY-MM-DD'),15);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (24,'유머','노래방 언제풀려?','대머리밀어라',to_date('2020-06-08','YYYY-MM-DD'),1248);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (25,'유머','포토샵 잘하는사람?','머스탱구리',to_date('2020-06-09','YYYY-MM-DD'),24);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (26,'유머','아직도 도로점거 하는 정신이상자들이 존재하나요?','문어대가리',to_date('2020-06-10','YYYY-MM-DD'),990);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (27,'구매후기','잔액부족으로 스팀어 2.2디제루 깡통 뽑았습니다','차거지',to_date('2020-06-11','YYYY-MM-DD'),5100);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (28,'비교/견적',' S클래스 풀체인지 eee','데일리카',to_date('2020-06-12','YYYY-MM-DD'),19);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (29,'유머','조언부탁드립니다','또기누기',to_date('2020-06-13','YYYY-MM-DD'),540);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (30,'비교/견적',' 225/45R17 vs 235/45R17','오니쯔',to_date('2020-06-14','YYYY-MM-DD'),771);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (31,'구매후기','쏘렌토 하이브리드 계약했습니다+_+','임프로',to_date('2020-06-15','YYYY-MM-DD'),3);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (32,'구매후기','플렉스*.*;;;;;','팬더마왕',to_date('2020-06-16','YYYY-MM-DD'),6678);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (33,'시승기','지금 순천 상사댐 와인딩 타는분들','망할에라이',to_date('2020-06-17','YYYY-MM-DD'),13270);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (34,'비교/견적','18년식 카마로 장기렌트 질문드립니다.','아잇너무행',to_date('2020-06-18','YYYY-MM-DD'),1112);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (35,'비교/견적','테슬라 차량 라인업','마력백프',to_date('2020-06-19','YYYY-MM-DD'),4141);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (12,'유머','와 헐 우리나라에서 오징어가 못생긴 이유 알아냈대(충격','내이름은오징어',to_date('2020-07-12','YYYY-MM-DD'),23);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (14,'시승기','잘 팔릴 수 밖에 없는 SUV,링컨 에비에이터 리저브 시승기','정명효도르',to_date('2020-07-14','YYYY-MM-DD'),0);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (15,'시승기','현대자동차 2014 제네시스 g380 시승기','심재봉봉',to_date('2020-07-15','YYYY-MM-DD'),4);
Insert into GREEN_ADMIN.COMMUNITY (COMMU_NO,COMMU_TAG,COMMU_TITLE,COMMU_WRITER,COMMU_DATE,COMMU_VIEW) values (16,'시승기','르노삼성 XM3시승기','누가나차사줘',to_date('2020-07-16','YYYY-MM-DD'),45);
REM INSERTING into GREEN_ADMIN.COMMUNITY_COMMENT
SET DEFINE OFF;
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (1,'순정마초',to_date('2020-07-02','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (2,'김시연',to_date('2020-07-02','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (3,'빨판오빠',to_date('2020-06-26','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (4,'헬창충충',to_date('2020-06-27','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (7,'카푸어',to_date('2020-05-23','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (13,'기므시여느',to_date('2020-04-17','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (14,'기므시여느',to_date('2020-04-18','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (15,'기므시여느',to_date('2020-03-27','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (16,'내가규림',to_date('2020-07-03','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (18,'민소희',to_date('2020-06-26','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (19,'운남소저',to_date('2020-06-27','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (20,'피지컬갤러리',to_date('2020-06-28','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (21,'닥터스',to_date('2020-06-29','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (22,'단발머리걔',to_date('2020-05-23','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (23,'럭셔리서예지',to_date('2020-05-24','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (24,'하체충',to_date('2020-05-25','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (26,'입매우긴햇님',to_date('2020-05-27','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (27,'만종원',to_date('2020-05-28','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (28,'나도조이',to_date('2020-04-17','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (29,'승우엄마',to_date('2020-04-18','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (30,'고무신',to_date('2020-03-27','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (31,'순정마초',to_date('2020-07-04','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (32,'나린아범',to_date('2020-07-04','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (33,'빨판오빠',to_date('2020-07-04','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (34,'헬창충충',to_date('2020-07-04','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (35,'이중주차',to_date('2020-04-28','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (36,'카이러케',to_date('2020-04-28','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (37,'카푸어',to_date('2020-05-23','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (38,'폴리주스',to_date('2020-05-24','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (39,'하고싶다',to_date('2020-05-25','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (40,'시연쨩',to_date('2020-05-26','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (41,'오박사',to_date('2020-05-27','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (42,'지우',to_date('2020-05-28','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (43,'피카츄',to_date('2020-05-29','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (44,'삼성맨',to_date('2020-05-30','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (45,'반박충',to_date('2020-05-31','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (46,'헬스빌런',to_date('2020-06-01','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (47,'반박충',to_date('2020-06-02','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (48,'지나가던1인',to_date('2020-06-03','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (49,'헬스빌런',to_date('2020-06-04','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (50,'중2병',to_date('2020-06-05','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (9,'카푸어',to_date('2020-05-25','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (10,'시연쨩',to_date('2020-05-26','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (11,'시연쨩',to_date('2020-05-27','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (12,'시연쨩',to_date('2020-05-28','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (5,'이중주차',to_date('2020-06-28','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (6,'카푸어',to_date('2020-06-29','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (8,'카푸어',to_date('2020-05-24','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (17,'윈도우아라',to_date('2020-07-02','YYYY-MM-DD'));
Insert into GREEN_ADMIN.COMMUNITY_COMMENT (COMM_NO,COMM_WRITER,COMM_DATE) values (25,'사이드레이즈',to_date('2020-05-26','YYYY-MM-DD'));
REM INSERTING into GREEN_ADMIN.GOODS
SET DEFINE OFF;
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (1,'포드 머스탱','중형','컨버터블',68500000,8,'휘발유',1,100001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (2,'포드 몬데오','중형','기타',41100000,15,'디젤',1,100002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (6,'GV80','준대형','컨버터블',60370000,9,'디젤',2,200001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (7,'G70','중형','세단',37770000,15,'디젤',2,200002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (8,'G80','중형','세단',52470000,15,'디젤',2,200003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (9,'G90','중형','세단',77070000,9,'디젤',2,200004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (10,'G100','대형','컨버터블',11000000,8,'디젤',2,200005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (11,'Accord','중형','세단',36100000,19,'휘발유',3,300001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (12,'PILOT','준대형','컨버터블',55700000,8,'휘발유',3,300002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (13,'CIVIC SPORT','준중형','기타',32100000,14,'디젤',3,300003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (14,'HR-V','중형','컨버터블',31200000,12,'가솔린',3,300004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (15,'ODYSSEY','소형','기타',56470000,9,'디젤',3,300005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (16,'아반떼','중형','세단',15700000,15,'가솔린',4,400001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (17,'i30','중형','쿠페',23790000,11,'가솔린',4,400002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (18,'벨로스터','중형','세단',20960000,13,'가솔린',4,400003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (19,'소나타','중형','세단',23860000,13,'가솔린',4,400004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (20,'그랜저','준대형','세단',32940000,11,'가솔린',4,400005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (21,'Q50','중형','세단',58400000,12,'디젤',5,500001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (22,'Q60','중형','컨버터블',68270000,10,'가솔린',5,500002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (23,'QX50','준대형','컨버터블',51270000,10,'디젤',5,500003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (24,'QX60','준대형','컨버터블',58470000,11,'가솔린',5,500004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (25,'Q70','대형','컨버터블',82470000,8,'디젤',5,500005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (26,'S8L','대형','세단',205000000,7.2,'가솔린',6,600001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (27,'S7','준대형','세단',118000000,12,'디젤',6,600002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (28,'S6','준대형','세단',18000000,11.4,'디젤',6,600003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (29,'Q3','준중형','SUV',50900000,14.3,'디젤',6,600004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (30,'A5','중형','세단',65900000,10.4,'가솔린',6,600005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (31,'E클래스','준대형','세단',36000000,9.2,'디젤,가솔린',7,700001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (32,'CLS클래스','준대형','세단',87500000,9.8,'디젤',7,700002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (33,'G클래스 AMG','중형','SUV',215000000,6.1,'가솔린',7,700003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (34,'마이바흐 S 클래스','대형','세단',245600000,6.3,'가솔린',7,700004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (35,'C클래스AMG','중형','세단',86400000,9.1,'가솔린',7,700005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (36,'에스컬레이드','대형','SUV',129800000,6.8,'가솔린',8,800001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (37,'XT5','중형','SUV',6717000,8,'가솔린',8,800002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (38,'CT6','대형','세단',89880000,8.7,'가솔린',8,800003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (39,'CT5','준대형','세단',54280000,10.2,'가솔린',8,800004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (40,'XT6','준대형','SUV',83470000,8.3,'가솔린',8,800005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (41,'트래버스','준대형','SUV',45200000,8.3,'가솔린',9,900001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (42,'스파크','경형','해치백',9770000,14.4,'가솔린',9,900002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (43,'콜로라도','준대형','기타',38550000,8.1,'가솔린',9,900003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (44,'이쿼녹스','중형','SUV',29450000,12.9,'디젤',9,900004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (45,'카마로','스포츠카','쿠페',53560000,7.4,'가솔린',9,900005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (46,'F8 스파이더','스포츠카','기타',397000000,5.6,'가솔린',10,1000001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (47,'F8트리뷰토','스포츠카','기타',352000000,6.6,'가솔린',10,1000002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (48,'GTC4 루쏘','스포츠카','기타',51270000,10,'디젤',10,1000003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (49,'포르토피노','스포츠카','기타',299000000,8.1,'가솔린',10,1000004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (50,'812슈퍼패스트','스포츠카','기타',471000000,5.6,'가솔린',10,1000005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (51,'셀토스','소형','suv',19340000,11,'디젤',11,1100001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (52,'쏘렌토','중형','suv',30240000,14,'디젤',11,1100002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (53,'카니발','대형','suv',28800000,8,'디젤',11,1100003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (54,'k3','소형','쿠페',37000000,13,'가솔린',11,1100004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (55,'k5','중형','세단',97000000,10,'가솔린',11,1100005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (56,'k7','준대형','컨버터블',60370000,7,'가솔린',11,1100006);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (57,'스팅어','중형','세단',37770000,15,'가솔린',11,1100007);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (58,'E-pace','중형','suv',55550000,9,'디젤',12,1200001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (59,'F-pace','대형','suv',72600000,8.5,'디젤',12,1200002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (60,'xe','중형','컨버터블',58500000,9.1,'휘발유',12,1200003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (61,'xf','준대형','세단',71900000,9.3,'휘발유',12,1200004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (62,'XJ','준대형','대형',150900000,8,'휘발유',12,1200005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (63,'URUS','대형','suv',255140000,6.3,'가솔린',13,1300001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (64,'Aventador','중형','스포츠카',577340000,4.4,'가솔린',13,1300002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (65,'Huracan EVO','소형','스포츠카',299000000,6,'가솔린',13,1300003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (66,'Hatch','소형','suv',32200000,11.3,'가솔린',14,1400001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (67,'Countryman','소형','suv',3940000,9.6,'가솔린',14,1400002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (68,'Clubman','소형','suv',36400000,10,'가솔린',14,1400003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (69,'Convertible','소형','suv',44000000,10.8,'가솔린',14,1400004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (70,'Electric','소형','suv',32940000,32.6,'전기',14,1400005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (71,'ES','준대형','세단',57500000,17,'가솔린',15,1500001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (72,'UX','중형','suv',45400000,15.9,'가솔린',15,1500002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (73,'NX','중형','suv',58100000,9.3,'가솔린',15,1500003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (74,'RX','대형','suv',81000000,8.9,'가솔린',15,1500004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (75,'LS','대형','세단',124700000,8,'가솔린',15,1500005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (76,'티볼리','소형','suv',28140000,14.5,'휘발유',16,1600001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (77,'코란도','중형','suv',32450000,15.6,'휘발유',16,1600002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (78,'렉스턴스포츠 칸','대형','픽업밴',36900000,10.3,'경유',16,1600003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (79,'렉스턴 스포츠','대형','픽업밴',34400000,11.3,'경유',16,1600004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (80,'G4렉스턴','대형','suv',46500000,10.5,'경유',16,1600005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (81,'Cybertruck','대형','픽업밴',85200000,18,'전기',17,1700001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (82,'Model Y','중형','suv',84000000,15,'전기',17,1700002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (83,'로드스터','중형','스포츠카',240000000,1000,'전기',17,1700003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (84,'Model X','준대형','suv',141600000,421,'전기',17,1700004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (85,'Model S','준대형','세단',138600000,480,'전기',17,1700005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (86,'2020프리우스C','소형','경차',25900000,18.6,'가솔린',18,1800001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (87,'2020캠리하이브리드','중형','세단',42900000,17.5,'가솔린,전기',18,1800002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (88,'2020 GR 수프라','준대형','스포츠카',73800000,9.7,'가솔린',18,1800003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (89,'2019 라브4 하이브리드','준중형','suv',46900000,15.9,'가솔린,전기',18,1800004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (90,'2019 아발론 하이브리드','준대형','세단',47400000,16.6,'가솔린,전기',18,1800005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (91,'2020 아테온','중형','세단',61130000,15.2,'디젤',19,1900001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (92,'2020 티구안 올스페이스','중형','suv',48270000,13.5,'디젤',19,1900002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (93,'2020 투아렉','준대형','suv',99470000,10.3,'디젤',19,1900003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (94,'2020 티구안','준중형','suv',47570000,14.5,'디젤',19,1900004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (95,'2016 골프','준중형','해치백',38800000,15.5,'경유',19,1900005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (96,'2020 XC60 플러그인 하이브리드','중형','suv',83200000,10.8,'가솔린,전기',20,2000001);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (97,'2020 XC40','준중형','suv',50800000,10.3,'가솔린',20,2000002);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (98,'2020 S90','준대형','세단',65900000,11,'가솔린',20,2000003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (99,'2020 S60','중형','세단',53600000,10.8,'가솔린',20,2000004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (100,'2020 XC90','준대형','suv',95500000,10.9,'디젤,가솔린',20,2000005);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (3,'포드 익스플로러','SUV','컨버터블',59200000,9,'디젤',1,100003);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (4,'포드 마카오','소형','쿠페',37000000,13,'전기',1,100004);
Insert into GREEN_ADMIN.GOODS (GOODS_NO,GOODS_NAME,GOODS_SIZE,GOODS_TYPE,GOODS_PRICE,GOODS_EFFICIENT,GOODS_FUEL,BRAND_CODE,GOODS_CODE) values (5,'포드 탱크','대형','세단',97000000,8,'휘발유',1,100005);
REM INSERTING into GREEN_ADMIN.GOODS_OPTION
SET DEFINE OFF;
Insert into GREEN_ADMIN.GOODS_OPTION (OPTION_NO,OPTION_NAME,OPTION_TIRE,OPTION_WHEEL,OPTION_NAVI,OPTION_SEAT,OPTION_FRAME,OPTION_WINDOW,OPTION_COST) values (1,'Basic','기본','기본','0','기본','알류미늄','접합 유리',0);
Insert into GREEN_ADMIN.GOODS_OPTION (OPTION_NO,OPTION_NAME,OPTION_TIRE,OPTION_WHEEL,OPTION_NAVI,OPTION_SEAT,OPTION_FRAME,OPTION_WINDOW,OPTION_COST) values (2,'Ultra','다이애거널','스포크','1','파워','카본','강화유리',3470000);
Insert into GREEN_ADMIN.GOODS_OPTION (OPTION_NO,OPTION_NAME,OPTION_TIRE,OPTION_WHEEL,OPTION_NAVI,OPTION_SEAT,OPTION_FRAME,OPTION_WINDOW,OPTION_COST) values (3,'Absolute','레이디얼','핀','1','메모리','카본','강화유리',2750000);
Insert into GREEN_ADMIN.GOODS_OPTION (OPTION_NO,OPTION_NAME,OPTION_TIRE,OPTION_WHEEL,OPTION_NAVI,OPTION_SEAT,OPTION_FRAME,OPTION_WINDOW,OPTION_COST) values (4,'Hybrid','튜브','메쉬','0','메모리','알류미늄','접합유리',520000);
Insert into GREEN_ADMIN.GOODS_OPTION (OPTION_NO,OPTION_NAME,OPTION_TIRE,OPTION_WHEEL,OPTION_NAVI,OPTION_SEAT,OPTION_FRAME,OPTION_WINDOW,OPTION_COST) values (5,'Hatch','튜브리스','디쉬','1','엑티브 헤드레스트','알류미늄','접합유리',1730000);
REM INSERTING into GREEN_ADMIN.NEWS
SET DEFINE OFF;
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (1,'안녕하세요. 안전하고 편리한 서비스를 제공하는 IT 기업 민앤지 로그인플러스입니다.');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (2,'우리는 사람의 조작 없이 차 스스로 운전하는 자동차가 현실로 마주하게 되었습니다.');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (3,'자율주행차의 필수조건이 커넥티비티 기술인데요. 초고속 무선통신을 이용해 자동차와 주변 모든 것을 연결하는 기술입니다.');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (4,'인터넷과 연결된 자동차는 편리해지는 만큼 해킹 위험 또한 함께 증가합니다.');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (5,'자동차의 미래');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (6,'현대자동차, 지역경제 활성화 위한 "상생 캠페인" 실시');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (7,'국고보조금이 해외로? 테슬라, 국내 소비자 차별 논란');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (8,'[자동차 경제학⑤] 쌍용자동차가 체어맨을 포기해야 하는 이유');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (9,'쌍용차의 브랜드 포지셔닝');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (10,'스마트폰 시장, 자동차 시장과 닮았다?');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (11,'기아차 카림 하비브 “포스트 코로나, 자동차 디자인 대변혁”');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (12,'코로나 19" 시대 자동차 디자인·기능 변화 예고...선두주자는?"');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (13,'자동차 디자인은 어떻게 변화되어 왔을까?');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (14,'OLED로 채워지는 자동차 디자인');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (15,'처음에는 어색했지만 점차 익숙해진 자동차 디자인 요소 TOP 5');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (16,'87년의 역사를 지닌 자동차 디자인, BMW 키드니 그릴');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (17,'이것은 침실인가? 자동차인가? 달라질 미래 자동차 디자인 베스트5');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (18,'“자동차 디자인=의사결정의 결과물!”');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (19,'나라의 상태가 투영되는 자동차 디자인');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (20,'자동차디자인은 언제부터 시작됐을까?');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (21,'현대자동차그룹, 강릉시와 함께 도시재생사업 나선다');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (22,'실제 주행가능거리는? 니우 엔프로');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (23,'정의선-최태원도 만났다..미래 전기차 배터리 협력 논의');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (24,'수입차 전시장, 세종시로 몰린다');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (25,'케이카 ""상반기 중고차 시장 4대 트렌드는..H.O.M.E""');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (26,'넥센타이어, 여름맞이 구매고객 대상 사은 이벤트');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (27,'자동차회사가 주목하는 엑소수트 이야기');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (28,'폭스바겐 공식딜러 유카로오토모빌, 울산 서비스센터 이전 오픈');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (29,'한성모터스, 여름맞이 7월 프로모션 진행');
Insert into GREEN_ADMIN.NEWS (NEWS_NO,NEWS_TITLE) values (30,'일론 머스크 ""올해 안에 5단계 자율주행 완성""');
REM INSERTING into GREEN_ADMIN.NOTICE
SET DEFINE OFF;
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (1,'2020년 7월 8일 클라이언트 로그인 불가 현상에 대한 안내 (정상화)','관리자',to_date('2020-07-03','YYYY-MM-DD'),37238);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (2,'6월 1주차 부정행위 프로그램 제재 현황 안내','관리자',to_date('2020-06-21','YYYY-MM-DD'),38247);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (3,'계정 운영 정책, 리그 오브 레전드 운영 정책 변경 안내','관리자',to_date('2020-06-15','YYYY-MM-DD'),8573);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (4,'전략적 팀 전투: 갤럭시 랭크 보상 업데이트','관리자',to_date('2020-05-21','YYYY-MM-DD'),93481);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (5,'2020년 6월 25일 상점 이용 불가 현상에 대한 안내 (정상화)','관리자',to_date('2020-04-17','YYYY-MM-DD'),7734);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (6,'PC 1.0 버전 패치노트 #7.3','관리자',to_date('2020-06-09','YYYY-MM-DD'),457842);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (7,'[안내] PUBG 개인정보 처리방침 개정 안내','관리자',to_date('2020-06-22','YYYY-MM-DD'),28275);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (8,'[개발일지] 안티치트 강화','관리자',to_date('2020-06-03','YYYY-MM-DD'),154842);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (9,'[개발일지] 여러분께 경쟁전을 소개합니다','관리자',to_date('2020-06-01','YYYY-MM-DD'),94445);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (10,'배틀그라운드 운영정책 개정 안내','관리자',to_date('2020-05-22','YYYY-MM-DD'),121587);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (11,'그린자동차 홈페이지 시스템 점검 일정 공지','관리자',to_date('2020-04-16','YYYY-MM-DD'),339);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (12,'코로나19 특별 보증 연장 안내','관리자',to_date('2020-04-02','YYYY-MM-DD'),1809);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (13,'그린닷컴 홈페이지 일부 서비스 일시 중단 안내','관리자',to_date('2020-03-03','YYYY-MM-DD'),4562);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (14,'제52기 정기주주총회 전자투표제도 및 위임장 안내','관리자',to_date('2020-05-21','YYYY-MM-DD'),1414);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (15,'디지털 키 서비스 일시 정지 안내','관리자',to_date('2020-02-24','YYYY-MM-DD'),345);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (16,'[정상화] iOS 환경에서 STOVE 앱 접속 불가 현상 안내(수정)','관리자',to_date('2020-07-08','YYYY-MM-DD'),10);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (17,'7월 9일(목) 클라이언트 패치 안내','관리자',to_date('2020-07-08','YYYY-MM-DD'),255);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (19,'STOVE OTP 신규 설정 시 페이지 갱신 문제 안내','관리자',to_date('2020-07-01','YYYY-MM-DD'),153);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (20,'불량 이용자 조치내역 안내','관리자',to_date('2020-05-01','YYYY-MM-DD'),215);
Insert into GREEN_ADMIN.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,UPLOAD_DATE,NOTICE_VIEW) values (18,'알려진 버그를 안내해 드립니다. (7/8 수정)','관리자',to_date('2020-07-05','YYYY-MM-DD'),23315);
REM INSERTING into GREEN_ADMIN.SALES_DATA
SET DEFINE OFF;
REM INSERTING into GREEN_ADMIN.USER_INFO
SET DEFINE OFF;
Insert into GREEN_ADMIN.USER_INFO (USER_NO,USER_EMAIL,USER_PW,USER_NICK,USER_BIRTH,USER_PH,USER_ADDRESS,USER_ADDRESS_DETAIL,USER_JOIN_DATE) values (9,'testuser09@greencar.com','aaaa009','테스트유저09',19900109,1033364139,'서울특별시 관악구 청룡중앙길42-9','201동 1514호',to_date('2020-05-09','YYYY-MM-DD'));
Insert into GREEN_ADMIN.USER_INFO (USER_NO,USER_EMAIL,USER_PW,USER_NICK,USER_BIRTH,USER_PH,USER_ADDRESS,USER_ADDRESS_DETAIL,USER_JOIN_DATE) values (1,'testuser01@greencar.com','aaaa001','테스트유저01',19900101,1033364131,'서울특별시 관악구 청룡중앙길42-1','201동 1506호',to_date('2020-05-01','YYYY-MM-DD'));
Insert into GREEN_ADMIN.USER_INFO (USER_NO,USER_EMAIL,USER_PW,USER_NICK,USER_BIRTH,USER_PH,USER_ADDRESS,USER_ADDRESS_DETAIL,USER_JOIN_DATE) values (2,'testuser02@greencar.com','aaaa002','테스트유저02',19900102,1033364132,'서울특별시 관악구 청룡중앙길42-2','201동 1507호',to_date('2020-05-02','YYYY-MM-DD'));
Insert into GREEN_ADMIN.USER_INFO (USER_NO,USER_EMAIL,USER_PW,USER_NICK,USER_BIRTH,USER_PH,USER_ADDRESS,USER_ADDRESS_DETAIL,USER_JOIN_DATE) values (3,'testuser03@greencar.com','aaaa003','테스트유저03',19900103,1033364133,'서울특별시 관악구 청룡중앙길42-3','201동 1508호',to_date('2020-05-03','YYYY-MM-DD'));
Insert into GREEN_ADMIN.USER_INFO (USER_NO,USER_EMAIL,USER_PW,USER_NICK,USER_BIRTH,USER_PH,USER_ADDRESS,USER_ADDRESS_DETAIL,USER_JOIN_DATE) values (4,'testuser04@greencar.com','aaaa004','테스트유저04',19900104,1033364134,'서울특별시 관악구 청룡중앙길42-4','201동 1509호',to_date('2020-05-04','YYYY-MM-DD'));
Insert into GREEN_ADMIN.USER_INFO (USER_NO,USER_EMAIL,USER_PW,USER_NICK,USER_BIRTH,USER_PH,USER_ADDRESS,USER_ADDRESS_DETAIL,USER_JOIN_DATE) values (5,'testuser05@greencar.com','aaaa005','테스트유저05',19900105,1033364135,'서울특별시 관악구 청룡중앙길42-5','201동 1510호',to_date('2020-05-05','YYYY-MM-DD'));
Insert into GREEN_ADMIN.USER_INFO (USER_NO,USER_EMAIL,USER_PW,USER_NICK,USER_BIRTH,USER_PH,USER_ADDRESS,USER_ADDRESS_DETAIL,USER_JOIN_DATE) values (6,'testuser06@greencar.com','aaaa006','테스트유저06',19900106,1033364136,'서울특별시 관악구 청룡중앙길42-6','201동 1511호',to_date('2020-05-06','YYYY-MM-DD'));
Insert into GREEN_ADMIN.USER_INFO (USER_NO,USER_EMAIL,USER_PW,USER_NICK,USER_BIRTH,USER_PH,USER_ADDRESS,USER_ADDRESS_DETAIL,USER_JOIN_DATE) values (7,'testuser07@greencar.com','aaaa007','테스트유저07',19900107,1033364137,'서울특별시 관악구 청룡중앙길42-7','201동 1512호',to_date('2020-05-07','YYYY-MM-DD'));
Insert into GREEN_ADMIN.USER_INFO (USER_NO,USER_EMAIL,USER_PW,USER_NICK,USER_BIRTH,USER_PH,USER_ADDRESS,USER_ADDRESS_DETAIL,USER_JOIN_DATE) values (8,'testuser08@greencar.com','aaaa008','테스트유저08',19900108,1033364138,'서울특별시 관악구 청룡중앙길42-8','201동 1513호',to_date('2020-05-08','YYYY-MM-DD'));
Insert into GREEN_ADMIN.USER_INFO (USER_NO,USER_EMAIL,USER_PW,USER_NICK,USER_BIRTH,USER_PH,USER_ADDRESS,USER_ADDRESS_DETAIL,USER_JOIN_DATE) values (10,'testuser10@greencar.com','aaaa010','테스트유저10',19900110,1033364140,'서울특별시 관악구 청룡중앙길42-10','201동 1515호',to_date('2020-05-10','YYYY-MM-DD'));
REM INSERTING into GREEN_ADMIN.USER_INQUIRY
SET DEFINE OFF;
Insert into GREEN_ADMIN.USER_INQUIRY (INQUIRY_NO,INQUIRY_TAG,INQUIRY_TITLE,INQUIRY_DATE,INQUIRY_WRITER) values (1,'자동차','차 바퀴가 배송이 안됬네요',to_date('2020-07-03','YYYY-MM-DD'),'알랍시여느');
Insert into GREEN_ADMIN.USER_INQUIRY (INQUIRY_NO,INQUIRY_TAG,INQUIRY_TITLE,INQUIRY_DATE,INQUIRY_WRITER) values (2,'자동차','문의>답변>재문의>재답변',to_date('2020-07-04','YYYY-MM-DD'),'알랍시여느');
Insert into GREEN_ADMIN.USER_INQUIRY (INQUIRY_NO,INQUIRY_TAG,INQUIRY_TITLE,INQUIRY_DATE,INQUIRY_WRITER) values (3,'자동차','차 바퀴가 왜 네모죠?',to_date('2020-07-03','YYYY-MM-DD'),'명효명존쎄');
Insert into GREEN_ADMIN.USER_INQUIRY (INQUIRY_NO,INQUIRY_TAG,INQUIRY_TITLE,INQUIRY_DATE,INQUIRY_WRITER) values (5,'자동차','자동차 이전 관련 문의',to_date('2020-07-04','YYYY-MM-DD'),'카푸어');
Insert into GREEN_ADMIN.USER_INQUIRY (INQUIRY_NO,INQUIRY_TAG,INQUIRY_TITLE,INQUIRY_DATE,INQUIRY_WRITER) values (6,'자동차','이거 너무 궁금합니다.',to_date('2020-07-04','YYYY-MM-DD'),'모하고사냐');
Insert into GREEN_ADMIN.USER_INQUIRY (INQUIRY_NO,INQUIRY_TAG,INQUIRY_TITLE,INQUIRY_DATE,INQUIRY_WRITER) values (7,'결제','결제가 안돼요',to_date('2020-07-12','YYYY-MM-DD'),'청담동주민');
--------------------------------------------------------
--  DDL for Index ADMIN_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."ADMIN_INFO_PK" ON "GREEN_ADMIN"."ADMIN_INFO" ("ADMIN_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007282
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."SYS_C007282" ON "GREEN_ADMIN"."ADMIN_INFO" ("ADMIN_NO", "ADMIN_EMAIL", "ADMIN_PW", "ADMIN_NICK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BRAND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."BRAND_PK" ON "GREEN_ADMIN"."BRAND" ("BRAND_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007292
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."SYS_C007292" ON "GREEN_ADMIN"."BRAND" ("BRAND_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NEWS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."NEWS_PK" ON "GREEN_ADMIN"."COMMUNITY" ("COMMU_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMUNITY_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."COMMUNITY_COMMENT_PK" ON "GREEN_ADMIN"."COMMUNITY_COMMENT" ("COMM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GOODS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."GOODS_PK" ON "GREEN_ADMIN"."GOODS" ("GOODS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007293
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."SYS_C007293" ON "GREEN_ADMIN"."GOODS" ("GOODS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GOODS_OPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."GOODS_OPTION_PK" ON "GREEN_ADMIN"."GOODS_OPTION" ("OPTION_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007305
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."SYS_C007305" ON "GREEN_ADMIN"."GOODS_OPTION" ("OPTION_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NOTICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."NOTICE_PK" ON "GREEN_ADMIN"."NOTICE" ("NOTICE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."USER_INFO_PK" ON "GREEN_ADMIN"."USER_INFO" ("USER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007276
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."SYS_C007276" ON "GREEN_ADMIN"."USER_INFO" ("USER_EMAIL", "USER_NICK", "USER_PH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_INQUIRY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."USER_INQUIRY_PK" ON "GREEN_ADMIN"."USER_INQUIRY" ("INQUIRY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMIN_INFO
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."ADMIN_INFO" MODIFY ("ADMIN_NO" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."ADMIN_INFO" MODIFY ("ADMIN_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."ADMIN_INFO" MODIFY ("ADMIN_PW" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."ADMIN_INFO" MODIFY ("ADMIN_NICK" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."ADMIN_INFO" ADD CONSTRAINT "ADMIN_INFO_PK" PRIMARY KEY ("ADMIN_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."ADMIN_INFO" ADD UNIQUE ("ADMIN_NO", "ADMIN_EMAIL", "ADMIN_PW", "ADMIN_NICK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BRAND
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."BRAND" MODIFY ("BRAND_NO" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."BRAND" ADD CONSTRAINT "BRAND_PK" PRIMARY KEY ("BRAND_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."BRAND" ADD UNIQUE ("BRAND_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMUNITY
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."COMMUNITY" MODIFY ("COMMU_NO" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY" MODIFY ("COMMU_TAG" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY" MODIFY ("COMMU_TITLE" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY" MODIFY ("COMMU_WRITER" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY" MODIFY ("COMMU_DATE" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY" ADD CONSTRAINT "NEWS_PK" PRIMARY KEY ("COMMU_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMUNITY_COMMENT
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."COMMUNITY_COMMENT" MODIFY ("COMM_NO" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY_COMMENT" MODIFY ("COMM_WRITER" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY_COMMENT" MODIFY ("COMM_TEXT" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY_COMMENT" MODIFY ("COMM_DATE" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."COMMUNITY_COMMENT" ADD CONSTRAINT "COMMUNITY_COMMENT_PK" PRIMARY KEY ("COMM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GOODS
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."GOODS" MODIFY ("GOODS_NO" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS" ADD CONSTRAINT "GOODS_PK" PRIMARY KEY ("GOODS_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."GOODS" ADD UNIQUE ("GOODS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GOODS_OPTION
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_NO" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_NAME" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_TIRE" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_WHEEL" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_NAVI" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_SEAT" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_FRAME" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_WINDOW" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" MODIFY ("OPTION_COST" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" ADD CONSTRAINT "GOODS_OPTION_PK" PRIMARY KEY ("OPTION_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."GOODS_OPTION" ADD UNIQUE ("OPTION_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NEWS
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."NEWS" MODIFY ("NEWS_TITLE" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."NEWS" MODIFY ("NEWS_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."NOTICE" MODIFY ("NOTICE_NO" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."NOTICE" MODIFY ("NOTICE_TITLE" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."NOTICE" MODIFY ("NOTICE_TEXT" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."NOTICE" MODIFY ("NOTICE_WRITER" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."NOTICE" ADD CONSTRAINT "NOTICE_PK" PRIMARY KEY ("NOTICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALES_DATA
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."SALES_DATA" MODIFY ("COLUMN1" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."SALES_DATA" MODIFY ("SALES_COST" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_INFO
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."USER_INFO" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."USER_INFO" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."USER_INFO" MODIFY ("USER_PW" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."USER_INFO" MODIFY ("USER_NICK" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."USER_INFO" ADD CONSTRAINT "USER_INFO_PK" PRIMARY KEY ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."USER_INFO" ADD UNIQUE ("USER_EMAIL", "USER_NICK", "USER_PH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_INQUIRY
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."USER_INQUIRY" MODIFY ("INQUIRY_NO" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."USER_INQUIRY" MODIFY ("INQUIRY_TAG" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."USER_INQUIRY" MODIFY ("INQUIRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."USER_INQUIRY" ADD CONSTRAINT "USER_INQUIRY_PK" PRIMARY KEY ("INQUIRY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
