--------------------------------------------------------
--  파일이 생성됨 - 일요일-7월-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."NOTICE" 
   (	"NOTICE_NO" NUMBER, 
	"NOTICE_TITLE" VARCHAR2(200 BYTE), 
	"NOTICE_TEXT" CLOB, 
	"NOTICE_WRITER" VARCHAR2(20 BYTE), 
	"UPLOAD_DATE" DATE DEFAULT sysdate, 
	"NOTICE_VIEW" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("NOTICE_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "GREEN_ADMIN"."NOTICE"."NOTICE_NO" IS '공지글번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."NOTICE"."NOTICE_TITLE" IS '공지글제목';
   COMMENT ON COLUMN "GREEN_ADMIN"."NOTICE"."NOTICE_TEXT" IS '공지글본문
';
   COMMENT ON COLUMN "GREEN_ADMIN"."NOTICE"."NOTICE_WRITER" IS '공지글작성자';
   COMMENT ON COLUMN "GREEN_ADMIN"."NOTICE"."UPLOAD_DATE" IS '공지글게시일';
   COMMENT ON COLUMN "GREEN_ADMIN"."NOTICE"."NOTICE_VIEW" IS '공지글조회수';
REM INSERTING into GREEN_ADMIN.NOTICE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index NOTICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."NOTICE_PK" ON "GREEN_ADMIN"."NOTICE" ("NOTICE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."NOTICE" ADD CONSTRAINT "NOTICE_PK" PRIMARY KEY ("NOTICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."NOTICE" MODIFY ("NOTICE_WRITER" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."NOTICE" MODIFY ("NOTICE_TEXT" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."NOTICE" MODIFY ("NOTICE_TITLE" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."NOTICE" MODIFY ("NOTICE_NO" NOT NULL ENABLE);
