--------------------------------------------------------
--  파일이 생성됨 - 일요일-7월-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_INFO
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."USER_INFO" 
   (	"USER_NO" NUMBER, 
	"USER_EMAIL" VARCHAR2(50 BYTE), 
	"USER_PW" VARCHAR2(50 BYTE), 
	"USER_NICK" VARCHAR2(50 BYTE), 
	"USER_BIRTH" NUMBER(8,0), 
	"USER_PH" NUMBER(11,0), 
	"USER_ADDRESS" VARCHAR2(50 BYTE), 
	"USER_ADDRESS_DETAIL" VARCHAR2(50 BYTE), 
	"USER_JOIN_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_NO" IS '고객번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_EMAIL" IS '고객메일아이디';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_PW" IS '고객비밇번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_NICK" IS '고객닉네임';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_BIRTH" IS '고객생년월일';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_PH" IS '고객핸드폰번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_ADDRESS" IS '고객 기본주소';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_ADDRESS_DETAIL" IS '고객 상세주소
';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INFO"."USER_JOIN_DATE" IS '고객가입일자';
REM INSERTING into GREEN_ADMIN.USER_INFO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index USER_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."USER_INFO_PK" ON "GREEN_ADMIN"."USER_INFO" ("USER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007276
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."SYS_C007276" ON "GREEN_ADMIN"."USER_INFO" ("USER_EMAIL", "USER_NICK", "USER_PH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USER_INFO
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."USER_INFO" ADD UNIQUE ("USER_EMAIL", "USER_NICK", "USER_PH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."USER_INFO" ADD CONSTRAINT "USER_INFO_PK" PRIMARY KEY ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."USER_INFO" MODIFY ("USER_NICK" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."USER_INFO" MODIFY ("USER_PW" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."USER_INFO" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."USER_INFO" MODIFY ("USER_NO" NOT NULL ENABLE);
