--------------------------------------------------------
--  파일이 생성됨 - 일요일-7월-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_INQUIRY
--------------------------------------------------------

  CREATE TABLE "GREEN_ADMIN"."USER_INQUIRY" 
   (	"INQUIRY_NO" NUMBER, 
	"INQUIRY_TAG" VARCHAR2(20 BYTE), 
	"INQUIRY_TITLE" VARCHAR2(100 BYTE), 
	"INQUIRY_TEXT" CLOB, 
	"INQUIRY_DATE" DATE DEFAULT sysdate, 
	"INQUIRY_WRITER" VARCHAR2(50 BYTE), 
	"INQUIRY_ANSWER" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("INQUIRY_TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("INQUIRY_ANSWER") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_NO" IS '고객문의번호';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_TAG" IS '문의유형';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_TITLE" IS '문의제목';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_TEXT" IS '문의본문';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_DATE" IS '문의일';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_WRITER" IS '문의고객명';
   COMMENT ON COLUMN "GREEN_ADMIN"."USER_INQUIRY"."INQUIRY_ANSWER" IS '문의답변';
REM INSERTING into GREEN_ADMIN.USER_INQUIRY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index USER_INQUIRY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GREEN_ADMIN"."USER_INQUIRY_PK" ON "GREEN_ADMIN"."USER_INQUIRY" ("INQUIRY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USER_INQUIRY
--------------------------------------------------------

  ALTER TABLE "GREEN_ADMIN"."USER_INQUIRY" ADD CONSTRAINT "USER_INQUIRY_PK" PRIMARY KEY ("INQUIRY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GREEN_ADMIN"."USER_INQUIRY" MODIFY ("INQUIRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."USER_INQUIRY" MODIFY ("INQUIRY_TAG" NOT NULL ENABLE);
  ALTER TABLE "GREEN_ADMIN"."USER_INQUIRY" MODIFY ("INQUIRY_NO" NOT NULL ENABLE);
